# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/turbo/Pulpit/github/MaxLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/turbo/Pulpit/github/MaxLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/turbo/Pulpit/github/MaxLib/CMakeFiles /home/turbo/Pulpit/github/MaxLib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/turbo/Pulpit/github/MaxLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/turbo/Pulpit/github/MaxLib/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MaxLib

# Build rule for target.
MaxLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaxLib
.PHONY : MaxLib

# fast build rule for target.
MaxLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaxLib.dir/build.make CMakeFiles/MaxLib.dir/build
.PHONY : MaxLib/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

src/GiString/GiString.o: src/GiString/GiString.cpp.o
.PHONY : src/GiString/GiString.o

# target to build an object file
src/GiString/GiString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaxLib.dir/build.make CMakeFiles/MaxLib.dir/src/GiString/GiString.cpp.o
.PHONY : src/GiString/GiString.cpp.o

src/GiString/GiString.i: src/GiString/GiString.cpp.i
.PHONY : src/GiString/GiString.i

# target to preprocess a source file
src/GiString/GiString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaxLib.dir/build.make CMakeFiles/MaxLib.dir/src/GiString/GiString.cpp.i
.PHONY : src/GiString/GiString.cpp.i

src/GiString/GiString.s: src/GiString/GiString.cpp.s
.PHONY : src/GiString/GiString.s

# target to generate assembly for a file
src/GiString/GiString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaxLib.dir/build.make CMakeFiles/MaxLib.dir/src/GiString/GiString.cpp.s
.PHONY : src/GiString/GiString.cpp.s

src/demo.o: src/demo.cpp.o
.PHONY : src/demo.o

# target to build an object file
src/demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaxLib.dir/build.make CMakeFiles/MaxLib.dir/src/demo.cpp.o
.PHONY : src/demo.cpp.o

src/demo.i: src/demo.cpp.i
.PHONY : src/demo.i

# target to preprocess a source file
src/demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaxLib.dir/build.make CMakeFiles/MaxLib.dir/src/demo.cpp.i
.PHONY : src/demo.cpp.i

src/demo.s: src/demo.cpp.s
.PHONY : src/demo.s

# target to generate assembly for a file
src/demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaxLib.dir/build.make CMakeFiles/MaxLib.dir/src/demo.cpp.s
.PHONY : src/demo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... MaxLib"
	@echo "... src/GiString/GiString.o"
	@echo "... src/GiString/GiString.i"
	@echo "... src/GiString/GiString.s"
	@echo "... src/demo.o"
	@echo "... src/demo.i"
	@echo "... src/demo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/turbo/Pulpit/github/MaxLib/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

